[package]
name = "geometric-centralities-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
webgraph = { git = "https://github.com/vigna/webgraph-rs.git" }
webgraph-algo = { path = "../webgraph-algo-rs" }
dsi-progress-logger = "0.2.4"
crossbeam-channel = "0.5.13"
atomic-counter = "1.0.1"
rayon = "1.10.0"
common_traits = "0.10.0"
env_logger = "0.11.5"
log = "0.4.22"
